In [1]:
import numpy as np
import pandas as pd
import scipy
import math
import random
import copy

# Example of a balanced matrix

In [ ]:
# Inputing balanced matrix as 
balanced_matrix = np.matrix(((1, 2, 4),(0.5, 1, 2), (0.25, 0.5, 1)))

In [3]:
# The matrix is balanced if M^2 - nM = 0
M = balanced_matrix**2 - balanced_matrix.shape[0] * balanced_matrix

if np.array_equal(M, np.zeros(shape = M.shape)):
    print(f"The given matrix is a balanced matrix.")

The given matrix is a balanced matrix.


In [4]:
# Calculate Luis matrix 
luis = M * np.transpose(M)
if np.array_equal(luis, np.zeros(shape=luis.shape)):
    print(f"There are no opportunities for arbitrage in this matrix.")
else:
    print(f"Arbitrage is a possibility in this matrix.")

with np.printoptions(precision=0, suppress=True):
    print(luis)

There are no opportunities for arbitrage in this matrix.
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Example with randomly generated matrix

In [5]:
A = np.random.random_sample(size = (7,7))*2

In [6]:
# The matrix is balanced if M^2 - nM = 0
M = A**2 - A.shape[0] * A

if np.array_equal(M, np.zeros(shape = M.shape)):
    print(f"The given matrix is a balanced matrix.")
elif not np.array_equal(M, np.zeros(shape = M.shape)):
    print(f"The given matrix is unbalanced.")
else:
    print(f"Unknown error encountered.")

The given matrix is unbalanced.


In [7]:
# Calculate Luis matrix 
luis = A * np.transpose(A)
if np.array_equal(luis, np.zeros(shape=luis.shape)):
    print(f"There are no opportunities for arbitrage in this matrix.")
else:
    print(f"Arbitrage is a possibility in this matrix.")
  
# Pretty matrix print
with np.printoptions(precision=0, suppress=True):
    print(luis)

Arbitrage is a possibility in this matrix.
[[0. 0. 0. 3. 2. 0. 1.]
 [0. 2. 1. 1. 1. 3. 0.]
 [0. 1. 1. 0. 0. 1. 1.]
 [3. 1. 0. 1. 2. 2. 2.]
 [2. 1. 0. 2. 1. 0. 0.]
 [0. 3. 1. 2. 0. 0. 2.]
 [1. 0. 1. 2. 0. 2. 1.]]


### Find the most profitable path 

In [8]:
np.where(luis == np.max(luis))

(array([1, 5], dtype=int64), array([5, 1], dtype=int64))