In [4]:
from forex_python.converter import CurrencyRates
import numpy as np
import pandas as pd
import scipy
import math
import random
import copy
import gzip, pickle, pickletools

# Skip to the bottom to run with previously-generated data.

* Uncomment and run cells to generate new data

# Example using forex-python to construct a current, real currency exchange matrix

In [2]:
%%time
####################################################################
# NOTE: SLOWER METHOD GETS MORE ACCURATE VALUES
# Generate a matrix with all the supported types of currency in
# forex-python module.
####################################################################

# # Obtain currency rates from forex-python module
# c = CurrencyRates()

# # Supported types of currency
# test_rates = c.get_rates(base_cur='USD')
# supported_types_of_currency = tuple(test_rates.keys())
# all_rates = c.get_rates(base_cur = 'EUR')

# # An empty array to hold the exchange data
# A = np.empty((33,33))


# # Save collected data into emtpy array
# for counter, item in enumerate(supported_types_of_currency):
#     all_rates = c.get_rates(base_cur=item)
# #     if item == 'EUR':
# #         print(item)
#     for counter_, item_ in enumerate(all_rates.keys()):
#         if counter == counter_:
#             A[counter, counter_] = 1
#         else:
#             A[counter, counter_] = all_rates.get(item_)
# #             if item_ == 'AUD':
# #                 print(item_, A[counter, counter_])            
            
# #             print(counter, counter_, item_)
            
# #     print(counter, counter_, item_)
            
            
# # Pretty print matrix a
# with np.printoptions(precision=4, suppress=True):
#     print(A)

####################################################################

Wall time: 0 ns


### Check if matrix is unbalanced

In [3]:
# # The matrix is balanced if A^2 - nA = 0
# M = np.multiply(A,A) - A.shape[0] * A

# # Check if matrix is balanced or unbalanced
# if np.array_equal(M, np.zeros(shape = M.shape)):
#     print(f"\nThe given matrix is a balanced matrix.\n")
# elif not np.array_equal(M, np.zeros(shape = M.shape)):
#     print(f"\nThe given matrix is unbalanced.\n")
# else:
#     print(f"\nUnknown error encountered.\n")
    
# # Pretty print M matrix
# with np.printoptions(precision=0, suppress=True):
#     print(M)

### Compute "luis" matrix

In [4]:
# # Calculate the "luis" matrix 
# luis = np.multiply(A, np.transpose(A))
# if np.array_equal(luis, np.zeros(shape=luis.shape)):
#     print(f"\nThere are no opportunities for arbitrage in this matrix.\n")
# else:
#     print(f"\nArbitrage IS a possibility in this matrix. Lucky you!\n")
    
# # Pretty print luis matrix
# with np.printoptions(precision=8, suppress=True):
#     print(luis)

### Using Pandas to check that the matrix looks like it's supposed to 

In [5]:
# luis[12,30]
# pd.DataFrame(luis)

### Slow but more accurate alternative to generate matrix A

In [6]:
%%time
####################################################################
# Generate a matrix with all the supported types of currency in
# forex-python module.
####################################################################

# # Empty matrix
# A = np.zeros((33,33))

# # Fill matrix with values
# for counter, item in enumerate(A):
# #     print(counter)
#     for counter_, item_ in enumerate(item):
#         # Choose one for those that are the same
#         if counter == counter_:
#             A[counter, counter_] = 1
#         else:
#             A[counter, counter_] = c.get_rate(base_cur=supported_types_of_currency[counter],
#                                                 dest_cur=supported_types_of_currency[counter_])


Wall time: 0 ns


In [7]:
####################################################################
# This saves generated matrix to a pickle file for faster 
# processing while loading and troubleshooting
####################################################################

# # Saving the matrix to a pickle file (for testing only)
# filepath = "data/test_matrix_optimized.pkl"
# with gzip.open(filepath, "wb") as f:
#     pickled = pickle.dumps(A)
#     optimized_pickle = pickletools.optimize(pickled)
#     f.write(optimized_pickle)
    
####################################################################

# =============================
# Start here - load previously generated data
# =============================

In [54]:
supported_types_of_currency = ['GBP', 'HKD', 'IDR', 'ILS', 'DKK', 'INR', 
                               'CHF', 'MXN', 'CZK', 'SGD', 'THB', 'HRK', 
                               'EUR', 'MYR', 'NOK', 'CNY', 'BGN', 'PHP', 
                               'PLN', 'ZAR', 'CAD', 'ISK', 'BRL', 'RON', 
                               'NZD', 'TRY', 'JPY', 'RUB', 'KRW', 'USD', 
                               'AUD', 'HUF', 'SEK']

In [55]:
####################################################################
# This loads the slowly simulated data to a variable A 
# for faster processing while troubleshooting
####################################################################

# Loading currency exchange matrix from a pickle file (for testing only)
filepath = "data/test_matrix_optimized.pkl"
with gzip.open(filepath, 'rb') as f:
    p = pickle.Unpickler(f)
    A = p.load()
    
####################################################################

In [56]:
# The matrix is balanced if A^2 - nA = 0
M = np.multiply(A,A) - A.shape[0] * A

# Check if matrix is balanced or unbalanced
if np.array_equal(M, np.zeros(shape = M.shape)):
    print(f"\nThe given matrix is a balanced matrix.\n")
elif not np.array_equal(M, np.zeros(shape = M.shape)):
    print(f"\nThe given matrix is unbalanced.\n")
else:
    print(f"\nUnknown error encountered.\n")
    
# Pretty print M matrix
with np.printoptions(precision=0, suppress=True):
    print(M)


The given matrix is unbalanced.

[[-3.e+01 -2.e+02  4.e+08 ... -6.e+01  1.e+05 -2.e+02]
 [-3.e+00 -3.e+01  4.e+06 ... -6.e+00  2.e+02 -4.e+01]
 [-2.e-03 -2.e-02 -3.e+01 ... -3.e-03 -7.e-01 -2.e-02]
 ...
 [-2.e+01 -2.e+02  1.e+08 ... -3.e+01  4.e+04 -2.e+02]
 [-8.e-02 -8.e-01  8.e+02 ... -1.e-01 -3.e+01 -1.e+00]
 [-3.e+00 -3.e+01  3.e+06 ... -5.e+00  6.e+01 -3.e+01]]


In [57]:
# Calculate the "luis" matrix 
luis = np.multiply(A, np.transpose(A))
if np.array_equal(luis, np.zeros(shape=luis.shape)):
    print(f"\nThere are no opportunities for arbitrage in this matrix.\n")
else:
    print(f"\nArbitrage IS a possibility in this matrix. Lucky you!\n")
    
# Pretty print luis matrix
with np.printoptions(precision=8, suppress=True):
    print(luis)


Arbitrage IS a possibility in this matrix. Lucky you!

[[1.         1.         0.99999979 ... 1.         1.         1.        ]
 [1.         1.         0.99999995 ... 1.         1.         1.        ]
 [0.99999979 0.99999995 1.         ... 0.99999972 1.         1.00000003]
 ...
 [1.         1.         0.99999972 ... 1.         1.00000001 1.        ]
 [1.         1.         1.         ... 1.00000001 1.         1.        ]
 [1.         1.         1.00000003 ... 1.         1.         1.        ]]


### Find the most profitable path

In [58]:
# Return the location where the maximum value of "luis" matrix occurs
result = np.where(luis == np.max(luis))
print(luis[result], result)
print(f"\nMost profitable bounce path is back and forth between {supported_types_of_currency[result[0][0]]} and {supported_types_of_currency[result[0][1]]}.\n")

[1.00000025 1.00000025] (array([ 2, 24], dtype=int64), array([24,  2], dtype=int64))

Most profitable bounce path is back and forth between IDR and NZD.



In [59]:
###########################################################################
# Find the most profitable transaction paths in the "Luis" matrix
# and then saves the pairs of most profitable transaction paths
# in a list of tuples 
###########################################################################

# Find the top three top max values by copying whole luis matrix
# and sequentially erasing the top value to find the next top value
luis_ = copy.deepcopy(luis)

max_values = np.empty(shape=(3,1))
max_locations = []
for i in range(3):
    # Find max and its index on matrix
    max_found = np.max(luis_)
    locations = np.where(luis_ == max_found)
    
    # Print maximums found
    print(f"Max number {i} is {max_found}")
    
    # Set max locations ot zero to find
    # the next maximum
    for v in locations:
        luis_[v] = 0
        
    # Collected the values maximum & one index
    max_values[i] = max_found
    max_locations.append(tuple(x for x in locations))

# Print most profitable transaction paths & collect names currencies. 
max_currency_names = []
for i in max_values:
    result = np.where(luis == i)
    print(f"Most profitable path is back and forth between "
          f"{supported_types_of_currency[result[0][0]]} "
          f"and {supported_types_of_currency[result[0][1]]}.")
    tmp_tuple = tuple([supported_types_of_currency[result[0][0]],
                       supported_types_of_currency[result[0][1]]])
    max_currency_names.append(tmp_tuple)

print(f"Saved names of currencies are: {max_currency_names}")

###########################################################################

Max number 0 is 1.0000002497908194
Max number 1 is 1.000000203786168
Max number 2 is 1.000000107314
Most profitable path is back and forth between IDR and NZD.
Most profitable path is back and forth between IDR and ILS.
Most profitable path is back and forth between IDR and EUR.
Saved names of currencies are: [('IDR', 'NZD'), ('IDR', 'ILS'), ('IDR', 'EUR')]


### Simulate a currency exchange with random path

In [60]:
#####################################################################################
# Simulate currency exchange with random path
#####################################################################################

# Parameters
investment = 100
t = 1000
fees = 1

# Money after the exchange using a random location
# USD -> EUR -> (CAD -> EUR)^t -> CAD -> USD
usd_ = supported_types_of_currency.index('USD')
eur_ = supported_types_of_currency.index('EUR')         # These two are the 
cad_ = supported_types_of_currency.index('CAD')         # most profitable transaction

# Exchange rates
usd_to_eur = A[usd_, eur_]
eur_to_usd = A[eur_, usd_]
eur_to_cad = A[eur_, cad_]
cad_to_eur = A[cad_, eur_]

# Calculate money after trade and the profit obtained
#                [in. conversion] [bounce between cad and eur] [convert back to usd]
result = investment * usd_to_eur * (eur_to_cad*cad_to_eur)**t * eur_to_usd * fees**t
profit = result - investment

print("Summary:\n"
      f"Initial investment of:                  ${investment}\n"
      f"Total number of iterations:             {t}\n"
      f"Percentage of total money lost to fees: {np.round((1-fees)*100)}%\n"
      f"Money after trade was concluded:        ${result}\n"
      f"Lost to fees:                           ${investment*(1-fees)}\n"
      f"Final profit:                           ${profit}")

#####################################################################################

Summary:
Initial investment of:                  $100
Total number of iterations:             1000
Percentage of total money lost to fees: 0%
Money after trade was concluded:        $99.99999604988868
Lost to fees:                           $0
Final profit:                           $-3.9501113207052185e-06


# Simulate a currency exchange with "Luis" path

In [61]:
#####################################################################################
# Simulate currency exchange with "Luis" path
#####################################################################################

# Parameters
investment = 1000
t = 300000
fees = 1

# Money after the exchange using luis path
one_ = supported_types_of_currency.index('ILS')
two_ = supported_types_of_currency.index('IDR')           # These two are the 
three_ = supported_types_of_currency.index('NZD')         # most profitable transaction

# Exchange rates
one_to_two = A[one_, two_]
two_to_one = A[two_, one_]
two_to_three = A[two_, three_]
three_to_two = A[three_, two_]

# Calculate money after trade and the profit obtained
#                [in. conversion] [bounce between cad and eur] [convert back to usd]
result = investment * one_to_two * (two_to_three*three_to_two)**t * two_to_one * fees
profit = result - investment

## VERIFY MOST REPEATED TRANSACTION IS MOST PROFITABLE TRANSACTION
assert two_to_three*three_to_two == np.max(luis)

print("Summary:\n"
      f"Initial investment of:                  ${investment}\n"
      f"Total number of iterations:             {t}\n"
      f"Percentage of total money lost to fees: {np.round((1-fees)*100)}%\n"
      f"Money after trade was concluded:        ${result}\n"
      f"Lost to fees:                           ${investment*(1-fees)}\n"
      f"Final profit:                           ${profit}")

#####################################################################################

Summary:
Initial investment of:                  $1000
Total number of iterations:             300000
Percentage of total money lost to fees: 0%
Money after trade was concluded:        $1077.8167208151979
Lost to fees:                           $0
Final profit:                           $77.81672081519787


In [62]:
# Double checking that assert statement is actually working
print(np.max(luis), two_to_three*three_to_two)

1.0000002497908194 1.0000002497908194


## A possibly even more profitable path

In [63]:
supported_types_of_currency_dict = dict(zip(supported_types_of_currency, range(len(supported_types_of_currency))))
print(supported_types_of_currency_dict.keys(), supported_types_of_currency_dict.values())

dict_keys(['GBP', 'HKD', 'IDR', 'ILS', 'DKK', 'INR', 'CHF', 'MXN', 'CZK', 'SGD', 'THB', 'HRK', 'EUR', 'MYR', 'NOK', 'CNY', 'BGN', 'PHP', 'PLN', 'ZAR', 'CAD', 'ISK', 'BRL', 'RON', 'NZD', 'TRY', 'JPY', 'RUB', 'KRW', 'USD', 'AUD', 'HUF', 'SEK']) dict_values([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32])


In [64]:
# Starting with dollars, find the values along the A matrix that have the largest
# coefficient going forward (i.e. a 1.02 for USD --> EUR)

# All values along "USD"
USD = A[supported_types_of_currency_dict.get('USD'),:]

# Values along the resulting currency with largest value above


In [65]:
USD

array([7.54306705e-01, 7.75038000e+00, 1.47385661e+04, 3.36716771e+00,
       6.28297585e+00, 7.31954062e+01, 9.11416990e-01, 2.15567472e+01,
       2.23230873e+01, 1.36446546e+00, 3.13899679e+01, 6.36632326e+00,
       8.44451951e-01, 4.14946800e+00, 8.93159939e+00, 6.84056747e+00,
       1.65157913e+00, 4.85813207e+01, 3.75899341e+00, 1.65747340e+01,
       1.30957609e+00, 1.39081236e+02, 5.30104712e+00, 4.09795643e+00,
       1.48961324e+00, 7.44933288e+00, 1.06223611e+02, 7.51334234e+01,
       1.18989191e+03, 1.00000000e+00, 1.37569667e+00, 3.03664921e+02,
       8.75595339e+00])